# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "lts-linux-firmware-mixin"
BBFILE_PATTERN_lts-linux-firmware-mixin = "^${LAYERDIR}/"
BBFILE_PRIORITY_lts-linux-firmware-mixin = "6"

LAYERSERIES_COMPAT_lts-linux-firmware-mixin = "wrynose"

LAYERDEPENDS_lts-linux-firmware-mixin = " \
    core \
"
